### ISSUE TITLE
add barchart grid

### ISSUE THREAD

**Issue by bstabler** [RSGInc/ABMVIZ#103]
add a CHART column to the bar chart data so we can generate a bar chart for each CHART.  The existing ARC data goes from:

```
PERSON GROUP, DAY PATTERN, Count
```
to
```
PERSON GROUP, DAY PATTERN, Count, Chart
```

**Comment by medailey** [comment]
question about this implementation, should the grid use the same set of checkbox controls, so if you check the box to rotate the chart to vertical all of the charts in the grid follow suit, or should each chart have it's own set of controls?

**Comment by bstabler** [comment]
Yes, the grid should use the same set of checkbox controls.
